name: CMake tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
